version: 2
jobs:
  build:
    working_directory: ~/pillar-authentication-sdk
    docker:
      - image: circleci/node:8.9.4
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
  test:
    working_directory: ~/pillar-authentication-sdk
    docker:
      - image: circleci/node:8.9.4
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install dependencies
          command: yarn install
      - run:
          name: yarn test
          command: yarn test
  publish:
    working_directory: ~/pillar-authentication-sdk
    docker:
      - image: circleci/node:8.9.4
    steps:
      - checkout
      - run:
          name: set Registry
          command: echo _auth = $ARTIFACTORY_PUBLISHING_USER:$ARTIFACTORY_PUBLISHING_PASSWORD https://pillarproject.jfrog.io/pillarproject/api/npm/auth >> .~/pillar-authentication-sdk/.npmrc
      - run:
          name: //TODO remove this
          command: cat ~/pillar-authentication-sdk/.npmrc
      - run:
          name: Publish Package to Artifactory
          command: npm publish   --registry https://pillarproject.jfrog.io/pillarproject/api/npm/npm/

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - publish:
          requires:
            - test
          filters:
            branches:
              only: ci_publish_to_artifactory
