version: 2
jobs:
  build:
    working_directory: ~/pillar-authentication-sdk
    docker:
      - image: circleci/node:8.9.4
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
  test:

    docker:
      - image: circleci/node:8.9.4
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install dependencies
          command: yarn install
      - run:
          name: yarn test
          command: yarn test
  publish:
    working_directory: ~/pillar-authentication-sdk
    docker:
      - image: circleci/node:8.9.4
    steps:
      - checkout
      - run:
          name: Append circleCI build number to version
          command: |
            git config user.email "devops@pillar.io"
            git config user.name "Issabot"
            npm version $(node -e "console.log( require('./package.json').version )")-$CIRCLE_BUILD_NUM
      - run:
            name: Authenticate with registry
            command: echo "//registry.npmjs.org/:_authToken=$PILLAR_NPM_TOKEN" > ~/pillar-authentication-sdk/.npmrc
      - run:
          name: Publish Package to Artifactory
          command: npm publish
      # - run:
      #     name: Announce Publish
      #     command: |
      #       chmod +x .circleci/announcePublish.sh
      #       .circleci/announcePublish.sh "auth SDK" "$(node -e "console.log(require('./package.json').name)")@$(node -e "console.log(require('./package.json').version)")"

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - publish:
          requires:
            - test
          filters:
            branches:
              only: master
